### ISSUE TITLE
Don't return 500 errors for "could not serialize access due to concurrent update"

### ISSUE THREAD

**Issue by emschwartz** [interledgerjs/five-bells-ledger#388]
Right now when the ledger runs into a `could not serialize access due to concurrent update` (with Postgres) it returns a 500 error to the user. It should probably retry the db query on its own. Otherwise, it should probably return something like a `503 Service Unavailable` rather than a generic 500.

**Comment by michielbdejong** [comment]
This was fixed, see [here](https://github.com/interledgerjs/five-bells-ledger/pull/408/files#diff-a94639f5e1b76fc887070e535f6521a3R206)
