### ISSUE TITLE
Query fails due to SQLITE_BUSY error

### ISSUE THREAD

**Issue by dappelt** [interledgerjs/five-bells-ledger#395]
If the ILP kit is running with sqlite, sometimes a SQL query of the ledger fails (full log [here](https://github.com/interledgerjs/five-bells-ledger/files/723299/debug.log.zip)):
```
ilp-kit[Wallet1] [ledger] 2017-01-23T10:26:22.426Z ledger:error-handler error { Error: update "L_TRANSFERS" set "EXECUTION_CONDITION" = 'cc:0:3:huknQrkt5DT-MI0hJf3b_xZhoDl5KT-07BFzWzaAuf0:32', "EXPIRES_DTTM" = '2017-01-23 11:26:32.348', "LEDGER" = 'https://wallet1.example/ledger', "PREPARED_DTTM" = '2017-01-23 11:26:22.374', "PROPOSED_DTTM" = '2017-01-23 11:26:22.362', "STATUS_ID" = 1, "TRANSFER_UUID" = '59c1c239-f6eb-4369-88c6-b657794cb1c3' where "TRANSFER_UUID" = '59c1c239-f6eb-4369-88c6-b657794cb1c3' - SQLITE_BUSY: database is locked
ilp-kit[Wallet1] [ledger]     at Error (native) errno: 5, code: 'SQLITE_BUSY' }
ilp-kit[Wallet1] [ledger] 2017-01-23T10:26:22.428Z ledger:error-handler error Error: update "L_TRANSFERS" set "EXECUTION_CONDITION" = 'cc:0:3:huknQrkt5DT-MI0hJf3b_xZhoDl5KT-07BFzWzaAuf0:32', "EXPIRES_DTTM" = '2017-01-23 11:26:32.348', "LEDGER" = 'https://wallet1.example/ledger', "PREPARED_DTTM" = '2017-01-23 11:26:22.374', "PROPOSED_DTTM" = '2017-01-23 11:26:22.362', "STATUS_ID" = 1, "TRANSFER_UUID" = '59c1c239-f6eb-4369-88c6-b657794cb1c3' where "TRANSFER_UUID" = '59c1c239-f6eb-4369-88c6-b657794cb1c3' - SQLITE_BUSY: database is locked
ilp-kit[Wallet1] [ledger]     at Error (native)
```

ILP kit, plugin-virtual, and ledger both use the same database. This error seems to happen if two processes try to modify the database at the same time.

**Comment by dappelt** [comment]
It turns out that sqlite does not support concurrent access to a database. Therefore, we should drop support for sqlite in ILP kit for production environments.

**Comment by justmoon** [comment]
@dappelt 

We already don't support it for production environments. I forget the exact reason, but I remember us concluding that SQLite would not be safe to use outside of testing and development. That's why we don't have migrations for SQLite, only for Postgres - for SQLite you just have to reset the DB when you upgrade.

I'd say it's time to consider dropping *all* support for SQLite.

**Comment by dappelt** [comment]
> I'd say it's time to consider dropping all support for SQLite.

Fine with me. Let me know if this decision is final. I am currently adding support for postgres in `five-bells-service-manager`. So the integration tests do not require sqlite anymore.
